version:"3.8"
services:
    server:
        build: .
        restart: always
        ports:
            - 8084:8084
        depends_on:
            - mysqldb
    mysqldb:
        image: "mysql:lastest"
        restart: always
        ports:
            - 3307:3306
        environments:
            MYSQL_DATABASE: thue_tncn
            MYSQL_USER: trando
            MYSQL_PASSWORD: trando
            MYSQL_ROOT_PASSWORD: trando
            